spring.application.name=U5Q7

spring.datasource.url=jdbc:mysql://localhost:3306/dbemp?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shriyash@11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true